name: push image to docker hub
on: 
  [workflow_dispatch]

jobs:
  
  push_image:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t ghcr.io/dataxsaiyan3/testing:latest
      - name: push
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u dataxsaiyan3 --password-stdin
          docker push ghcr.io/dataxsaiyan3/testing:latest